UWULogsData = {}
UWULogsData[5] = UWULogsData[5] or {}
UWULogsData[5][3] = {}
UWULogsData[2] = UWULogsData[2] or {}
UWULogsData[2][1] = {}
UWULogsData[4] = UWULogsData[4] or {}
UWULogsData[4][3] = {}
UWULogsData[6] = UWULogsData[6] or {}
UWULogsData[6][3] = {}
UWULogsData[2] = UWULogsData[2] or {}
UWULogsData[2][3] = {}
UWULogsData[5] = UWULogsData[5] or {}
UWULogsData[5][1] = {}
UWULogsData[8] = UWULogsData[8] or {}
UWULogsData[8][1] = {}
UWULogsData[0] = UWULogsData[0] or {}
UWULogsData[0][1] = {}
UWULogsData[6] = UWULogsData[6] or {}
UWULogsData[6][1] = {}
UWULogsData[0] = UWULogsData[0] or {}
UWULogsData[0][3] = {}
UWULogsData[4] = UWULogsData[4] or {}
UWULogsData[4][1] = {}
UWULogsData[9] = UWULogsData[9] or {}
UWULogsData[9][2] = {}
UWULogsData[6] = UWULogsData[6] or {}
UWULogsData[6][2] = {}
UWULogsData[0] = UWULogsData[0] or {}
UWULogsData[0][2] = {}
UWULogsData[4] = UWULogsData[4] or {}
UWULogsData[4][2] = {}
UWULogsData[8] = UWULogsData[8] or {}
UWULogsData[8][2] = {}
UWULogsData[8] = UWULogsData[8] or {}
UWULogsData[8][3] = {}
UWULogsData[1] = UWULogsData[1] or {}
UWULogsData[1][1] = {}
UWULogsData[9] = UWULogsData[9] or {}
UWULogsData[9][3] = {}
UWULogsData[7] = UWULogsData[7] or {}
UWULogsData[7][3] = {}
UWULogsData[1] = UWULogsData[1] or {}
UWULogsData[1][2] = {}
UWULogsData[1] = UWULogsData[1] or {}
UWULogsData[1][3] = {}
UWULogsData[2] = UWULogsData[2] or {}
UWULogsData[2][2] = {}
UWULogsData[7] = UWULogsData[7] or {}
UWULogsData[7][2] = {}
UWULogsData[5] = UWULogsData[5] or {}
UWULogsData[5][2] = {}
UWULogsData[3] = UWULogsData[3] or {}
UWULogsData[3][1] = {}
UWULogsData[3] = UWULogsData[3] or {}
UWULogsData[3][2] = {}
UWULogsData[7] = UWULogsData[7] or {}
UWULogsData[7][1] = {}
UWULogsData[9] = UWULogsData[9] or {}
UWULogsData[9][1] = {}
UWULogsData[3] = UWULogsData[3] or {}
UWULogsData[3][3] = {}